## DATASET DOWNLOAD CONFIGURATION ##
geojson_path: data/california.json
start_date: 2020-01-01
end_date: 2020-01-04
output_folder: data
db_path: confoundry_db.duckdb
show_progress: true


# Downloader configuration
downloaders:
  era5:
    enabled: false
    variables_dict:
      "t2m": "2m_temperature" 
      "ssrd": "surface_solar_radiation_downwards"
      "tp": "total_precipitation"
      "swvl1": "volumetric_soil_water_layer_1"
    # add other downloader-specific kwargs here
  modis_ndvi:
    enabled: false
    # add other downloader-specific kwargs here
  sen3_openeo:
    enabled: false
    # add other downloader-specific kwargs here
  sen3_eodag:
    enabled: true
    # add other downloader-specific kwargs here


# Maps variable names to more descriptive names for use in the dataset
name_map:
    2m_temperature: temperature
    total_precipitation: precipitation
    potential_evaporation: evaporation
    volumetric_soil_water_layer_2: soil_moisture_7_to_28_cm
    volumetric_soil_water_layer_3: soil_moisture_28_to_100_cm
    modis_ndvi: ndvi
reference_var: ndvi
columns:
    - name: temperature
      shift: 0
    - name: precipitation
      shift: 0
    - name: evaporation
      shift: 0
    - name: soil_moisture_7_to_28_cm
      shift: 0
    - name: soil_moisture_28_to_100_cm
      shift: 0
    - name: ndvi
      shift: -1
    - name: month_sin
      shift: 0
    - name: month_cos
      shift: 0